modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = ""

[[mods]]
modId = "vulkanmod"
version = "${version}"
displayName = "Example Mod"
authors = "Collateral"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.vulkanmod]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vulkanmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"